Add Users API examples
zoom-lib-golang/zoom-lib-golang pull request #30
Opened 2022-10-04 13:58 UTC by S-H-GAMELINKS

Hi.

I added Users API ezample in `__example/users`.

2022-10-15 17:21 UTC, rafecolton requested changes
Thanks for the contribution! Requesting a few minor changes 🙂

2022-10-15 17:21 UTC, rafecolton commented on .codeclimate.yml
> +  - "_example/users/*.go"
Please add a newline to the end of the file (not a blankline, just a newline) - it should be a setting in your editor

2022-10-15 17:21 UTC, rafecolton commented on _example/users/delete_user.go
> +	log.Printf("Resopnse: %+v\n", response)
Calling the return value `response` is a bit misleading IMO as it is not a response object (i.e. a user), the return value is only error. 

Would like to see it more like this:

```golang
if err := zoom.DeleteUser(opt); err != nil {
    log.Printf("Error: %+v\n", err)
}

2022-10-15 17:21 UTC, rafecolton commented on _example/users/get_user.go
> +	response, err := zoom.GetUser(opt)
Please use `user` here instead of `response`

2022-10-15 17:21 UTC, rafecolton commented on _example/users/get_user.go
> +	response, err = zoom.GetUser(opt)
Same, please use `user` here

2022-10-15 17:21 UTC, rafecolton commented on _example/users/get_users_list.go
> +	res, err := zoom.ListUsers(opt)
Use a more descriptive variable name please (`listUsersResponse` perhaps or at least fully spell out `response`)

2022-10-16 08:16 UTC, S-H-GAMELINKS commented
@rafecolton 
Thanks for your review comments!
It's done!

2022-10-16 22:52 UTC, rafecolton approved these changes

2022-10-16 22:52 UTC, merged