Add Meetings API examples
zoom-lib-golang/zoom-lib-golang pull request #32
Opened 2022-10-17 12:58 UTC by S-H-GAMELINKS

Hi.

I added Meetings API example in `__example/meetings`.
I'd be glad to merge these example.

2022-10-31 11:35 UTC, S-H-GAMELINKS commented
@rafecolton
Hi.
How is this pull request?

2022-11-04 00:08 UTC, rafecolton requested changes
Requesting one small change, everything else LGTM

2022-11-04 00:08 UTC, rafecolton commented on _example/meetings/delete_meeting.go
> +	if err != nil {
Please prefer abbreviated syntax here:

```suggestion
	if err = zoom.DeleteMeeting(deleteMeetingOpt); err != nil {
```

2022-11-09 13:08 UTC, S-H-GAMELINKS commented
@rafecolton 
Hi.
Thanks for your review comment!

Fixed it in https://github.com/zoom-lib-golang/zoom-lib-golang/pull/32/commits/54bd9af1d412ef0bdb0767ce2ff458e8c7c526bf

2022-11-09 14:55 UTC, rafecolton approved these changes

2022-11-09 14:55 UTC, merged